name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next
      
      - name: Install dependencies
        run: npm ci
      
      # Try using the Nx export command directly
      - name: Export Next.js site with Nx
        run: |
          echo "NODE_ENV=production" >> $GITHUB_ENV
          npx nx export personal-portfolio --prod
      
      # Find the export output directory
      - name: Find export output
        id: find-output
        run: |
          echo "Looking for export output..."
          
          # Check common export paths
          if [ -d "dist/apps/personal-portfolio/exported" ]; then
            echo "EXPORT_DIR=dist/apps/personal-portfolio/exported" >> $GITHUB_ENV
            echo "Export found at dist/apps/personal-portfolio/exported"
          elif [ -d "dist/apps/personal-portfolio/out" ]; then
            echo "EXPORT_DIR=dist/apps/personal-portfolio/out" >> $GITHUB_ENV
            echo "Export found at dist/apps/personal-portfolio/out"
          elif [ -d "apps/personal-portfolio/out" ]; then
            echo "EXPORT_DIR=apps/personal-portfolio/out" >> $GITHUB_ENV
            echo "Export found at apps/personal-portfolio/out"
          else
            echo "Searching for out directory recursively..."
            OUT_DIR=$(find . -type d -name "out" | grep -v node_modules | head -n 1)
            
            if [ -n "$OUT_DIR" ]; then
              echo "EXPORT_DIR=$OUT_DIR" >> $GITHUB_ENV
              echo "Export found at $OUT_DIR"
            else
              echo "No export directory found. Looking for any HTML files..."
              HTML_DIR=$(find dist -name "*.html" | head -n 1 | xargs dirname || echo "")
              
              if [ -n "$HTML_DIR" ]; then
                echo "EXPORT_DIR=$HTML_DIR" >> $GITHUB_ENV
                echo "HTML files found at $HTML_DIR"
              else
                echo "ERROR: Could not find export output!"
                find dist -type d | sort
                exit 1
              fi
            fi
          fi
      
      # Validate the export directory
      - name: Validate export directory
        run: |
          if [ -z "$EXPORT_DIR" ]; then
            echo "ERROR: Export directory not found!"
            exit 1
          fi
          
          echo "Checking export directory: $EXPORT_DIR"
          ls -la $EXPORT_DIR
          
          if [ ! -f "$EXPORT_DIR/index.html" ]; then
            echo "ERROR: index.html not found in export directory!"
            exit 1
          fi
      
      # Add .nojekyll file
      - name: Add .nojekyll file
        run: |
          touch $EXPORT_DIR/.nojekyll
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.EXPORT_DIR }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id:<span class="ml-2" /><span class="inline-block w-3 h-3 rounded-full bg-neutral-a12 align-middle mb-[0.1rem]" />
